keys:
  - &op age1gzwt92787quhql8et62t4a58yvkxscau2tat3ut7s0zya44qjdysw8f4cz
  - &nyx age16wp5ekk8tv498795f6unq2h9rzq7cdf3d2end8mkqpnx2zzlvehq5fh4w9
  - &bjorn age1uzgkggnjz40mhcryent23vpjm5utej4ad0z6emlc26falukx05ssp4heav
  - &framework13 age1d0496xph6fsq3usd7g7ryrhd5gwkv9fduwdqc0ew6rmjd5fegffqq3telq
creation_rules:
  - path_regex: secrets.yml
    key_groups:
    - age:
      - *op
      - *nyx
      - *bjorn
      - *framework13
  